version: '3.4'

services:
  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:    
      context: .
      dockerfile: WebApplication2/Dockerfile
    depends_on: 
    - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WeatherForecastDb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
   
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 5000:80
    volumes:
      - ./data:/var/lib/pgadmin
   

